### ISSUE TITLE
JLine-Command handling of unknown commands

### ISSUE THREAD

**Issue by orion-tran** [wherkamp/jline-command#2]
Instead of allowing the user to handle the unknown command, JLine-Command throws an NPE at these lines:

```
Exception in thread "Thread-1" java.lang.NullPointerException
    at me.kingtux.jlinecommand.JlineCommandManager.runCommand(JlineCommandManager.java:56)
    at me.kingtux.jlinecommand.JlineCommandManager.run(JlineCommandManager.java:106)
```

**Comment by wherkamp** [comment]
Sounds like a personal problem. Probably will be fixed tomorrow.

**Comment by wherkamp** [comment]
It is a personal problem. Update to 1.1. :wobble:
